### ISSUE TITLE
Is your init.sh working for you?

### ISSUE THREAD

**Issue by tannert44** [winstonhong/Shibboleth-SAML-IdP-and-SP#6]
Hello, 

I've seen you posting this everywhere, but as someone extremely new to docker, SAML, and Shibboleth. I've only be able to get your example working so long as I added your sp.example.org and idp.example.org to my host file, but when I try to run your init.sh things are not going like I would expect given your readme. Why does the init-idp.sh in the bin folder try to cd into a non-existent folder /opt/shibboleth-idp/bin?

Sorry if this is a basic question, but trying to figure out if I need to modify this file or change the directory structure in someway to match it.

**Comment by winstonhong** [comment]
Thanks for using our Docker-based Shibboleth testbed.

(1) README provided by the home folder "Shibboleth-SAML-IdP-and-SP" instructs a user how to build a Docker-based Shibboleth testbed with the default configuration such as the host name "idp.example.com".

(2) README provided by the sub-folder "shibboleth-idp-dockerized" instructs a user how to build a Docker-based Shibboleth testbed with the configuration set by you.

(3) You need to run the command "./build.sh" to build a Docker image of Shibboleth IdP 

before you run the command "./init.sh" 

The folder "/opt/shibboleth-idp/bin" exists inside the Shibboleth IdP docker container "example/shibboleth-idp:latest"

For example, the following command in the sub-folder "shibboleth-idp-dockerized/bin/init-idp.sh"

echo "Please complete the following for your IdP environment:"

instructs a user to input the configuration of Shibboleth IdP (such as the host name "idp.example.com")

to generate the metadata of Shibboleth IdP.

Remarks:

This Docker-based Shibboleth testbed has been validated in Ubuntu 14.04/16.04/18.04. 

I will validate the testbed in Ubuntu 20.04 when I provide new update in the future.

**Comment by tannert44** [comment]
So I'll give you some screenshots. The main issue I am having is that the init.sh does not seem to recreate the ext-conf file like your documentation says:

"If you want to create your own Shibboleth IDP configuration, you can delete the existing directory './ext-conf' and then create a starting set of configuration files by running: ./init.sh"

Below are the steps I followed:

1.  Clone a fresh version of the repo
2.  Change directories to LDAP
3.  Build and run the LDAP server with ./build.sh and ./run.sh
4.  Change directories to shibboleth-idp-dockerized
5.  Build the shibboleth-idp-dockerized with ./build.sh
6.  Delete the ext-conf file
7.  Run init.sh
8.  Answer questions


Results:

![ShibIdpIssues](https://user-images.githubusercontent.com/12992361/113572104-384fd880-95dd-11eb-9fc7-d087e1d9e845.PNG)

**Comment by tannert44** [comment]
So I'll give you some screenshots, and you can tell me if I am just expecting more from the docs than I should be

Below are the steps I followed:

1. Clone a fresh version of the repo
2. Change directories to LDAP
3. Build and run the LDAP server with ./build.sh and ./run.sh
4. Change directories to shibboleth-idp-dockerized
5. Build the shibboleth-idp-dockerized with ./build.sh
6. Delete the ext-conf file
7. Run init.sh
8. Answer questions

Results:

![ShibIdpIssues](https://user-images.githubusercontent.com/12992361/113572622-35091c80-95de-11eb-8ec5-c69a9db0e967.PNG)

The metadata folder is empty and the conf folder is empty. Maybe they're supposed to be empty, but Step 4 on shibboleth-idp-dockerized mentions the ext-conf/conf/ldap.properties file which is no longer present, so I felt like something was going wrong. Is this the expected behavior?

**Comment by tannert44** [comment]
I've got everything resolved. However, I followed the steps above again later today, and I didn't get an ext-conf file generated at all. So I feel like there is something going on either on my local machine or with the init process itself. I've got this working by just using the default ext-conf as a base and working from there on reconfiguring.
