### ISSUE TITLE
./run.sh shibboleth-sp-testapp stuck

### ISSUE THREAD

**Issue by salibeh** [winstonhong/Shibboleth-SAML-IdP-and-SP#7]
Tried Ubuntu 18.04 and 16.04.

The builds and runs for LDAP-Dockerized-CentOS and shibboleth-idp-docker-dockerized were successful.
The build for shibboleth-sp-testapp was successful.  However, the run for the same resulted in the following:

checkout@ubuntu:~/Shibboleth-SAML-IdP-and-SP/shibboleth-sp-testapp$ ./run.sh 
Starting shibd:                                            [  OK  ]
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
httpd-error [Thu Dec 23 01:18:14.015082 2021] [suexec:notice] [pid 1:tid AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
httpd-ssl-error [Thu Dec 23 01:18:14.016323 2021] [ssl:warn] [pid 1:tid AH01909: RSA certificate configured for 172.17.0.4:443 does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
httpd-error [Thu Dec 23 01:18:14.050036 2021] [auth_digest:notice] [pid 1:tid AH01757: generating secret for digest authentication ...
httpd-error [Thu Dec 23 01:18:14.051133 2021] [lbmethod_heartbeat:notice] [pid 1:tid AH02282: No slotmem from mod_heartmonitor
httpd-ssl-error [Thu Dec 23 01:18:14.053195 2021] [ssl:warn] [pid 1:tid AH01909: RSA certificate configured for 172.17.0.4:443 does NOT include an ID which matches the server name
httpd-error [Thu Dec 23 01:18:14.081704 2021] [mpm_prefork:notice] [pid 1:tid AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips configured -- resuming normal operations
httpd-error [Thu Dec 23 01:18:14.092330 2021] [core:notice] [pid 1:tid AH00094: Command line: 'httpd -D FOREGROUND'
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 01:18:14 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 01:18:14 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites

The run got stuck!

I tried https://sp.example.org:2443
and got:   Check if there is a typo in idp.example.com.

I tried https://localhost:2443
and got the login link
when clicked on login
and got: Check if there is a typo in idp.example.com

I appreciate your help.

**Comment by winstonhong** [comment]
Quote the info from your log "AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message"

Please insert the following info into the host file of the machine where your web browser (such as Chrome, Edge or Firefox) is located. For example, in my Windows machine, I edit the file "C:\Windows\System32\Drivers\etc\hosts"

`172.17.0.4 sp.example.org idp.example.com`

**Comment by salibeh** [comment]
Thanks for the tip.

172.17.0.4 sp.example.org idp.example.com does not work.
but 172.17.0.1 does work (this is the ip addr of the docker0 interface on the host (ubuntu 18.040.
Note that 172.17.0.4 is assigned to the shibboleth-sp container on the inside.

Neither resolves the issues raised on executing ./run.sh of the shibboleth-sp. Here are the debug messages:
checkout@ubuntu:~/Shibboleth-SAML-IdP-and-SP/shibboleth-sp-testapp$ ./run.sh 
Starting shibd:                                            [  OK  ]
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
httpd-error [Thu Dec 23 15:53:52.879077 2021] [suexec:notice] [pid 1:tid AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
httpd-ssl-error [Thu Dec 23 15:53:52.882058 2021] [ssl:warn] [pid 1:tid AH01909: RSA certificate configured for 172.17.0.4:443 does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
httpd-error [Thu Dec 23 15:53:52.912436 2021] [auth_digest:notice] [pid 1:tid AH01757: generating secret for digest authentication ...
httpd-error [Thu Dec 23 15:53:52.913492 2021] [lbmethod_heartbeat:notice] [pid 1:tid AH02282: No slotmem from mod_heartmonitor
httpd-ssl-error [Thu Dec 23 15:53:52.914850 2021] [ssl:warn] [pid 1:tid AH01909: RSA certificate configured for 172.17.0.4:443 does NOT include an ID which matches the server name
httpd-error [Thu Dec 23 15:53:52.921559 2021] [mpm_prefork:notice] [pid 1:tid AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips configured -- resuming normal operations
httpd-error [Thu Dec 23 15:53:52.922029 2021] [core:notice] [pid 1:tid AH00094: Command line: 'httpd -D FOREGROUND'
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 15:53:53 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 15:53:53 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : insecure cookieProps setting, set to "https" for SSL/TLS-only usage
sp-native 2021-12-23 15:53:53 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites

I appreciate your help in resolving these issues

**Comment by winstonhong** [comment]
I pull the docker image "unicon/shibboleth-sp" from Docker repository, which was built using the following Docker file in July 2019.
https://github.com/Unicon/shibboleth-sp-dockerized/blob/master/Dockerfile

If you want to remove the error message, you need to use the above Dockerfile to build the local Docker image as "unicon/shibboleth-sp", and then re-build the Shibboleth SP image by running the command "./build" again.

Note that these error messages are caused by Apache. You can fix the error message by following the instruction provided by the following link. 
https://unix.stackexchange.com/questions/441648/centos7-apache-rsa-certificate-does-not-include-an-id-which-matches-the-server

You need to copy the Apache configuration from the local directory into the same Apache directory inside the Docker container when you build the Docker image. Another solution is that you just modify the ./run.sh to copy the Apache configuration from the local directory into the same Apache directory inside the Docker container.

However, these error messages do NOT affect the Shibboleth SAML demo. I have validated the README using the Firefox web browser on Ubuntu 20.04 and Chrome/Firefox web browser on Windows 10 machine.

**Comment by salibeh** [comment]
Thank you very much for your answer and suggestions regarding the need for updating the apache configuration.

I consider the original issue resolved based on your overall input.  Thanks again.
